sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t ademola123/front .

script:
  - docker run -e CI=true ademola123/front npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Docker-testing"
  env: "Docker-testing-env"
  bucket_name: "elasticbeanstalk-us-west-2-130002661268"
  bucket_path: "Docker-testing"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
